Numix-Circle/48x48/apps/openscad.svg
Fixed the overly harsh gradient (was 30L)
Before:
After:
=> OpenSCAD icon gradient fix

Numix-Circle/48x48/apps/subtitleeditor.svg
Fixed subtitleeditor link which was pointing to non-existing *gnome-subtitle.svg* . Fixes issue #1480
=> Fixed subtitleeditor link. Fixes #1480

Numix-Circle/48x48/apps/armoryicon.svg, Numix-Circle/48x48/apps/armoryofflineicon.svg, Numix-Circle/48x48/apps/armorytestneticon.svg
Icons for Armory, issue #1226
armoryicon:
armoryofflineicon:
armorytestneticon:
=> Icons for Armory. Fixes #1226

Numix-Circle/48x48/apps/QMapShack.svg, Numix-Circle/48x48/apps/qlandkartegt.svg
Icons for QLandkarteGT and QMapShack, issue #1034.
Icons as symbolic links to the existing Viking icon.
=> Icons for QLandkarteGT and QMapShack. Fixes #1034

Numix-Circle/48x48/apps/retext.svg
=> Icon for ReText. Fixes #1425

Numix-Circle/48x48/apps/qdbusviewer.svg
Made a symlink instead of entirely deleting *qtdbusviewer.svg* for as far as I can see its long name is actually "Qt D-Bus Viewer". Maybe the icon is called accordingly somewhere.
http://qt-project.org/doc/qt-4.8/qdbusviewer.html
=> Symlink for qdbusviewer. Fixes #1491

Numix-Circle/48x48/apps/translator.svg
Icon for Translator, issue #1465
Pushed:
Alternative background:
=> Icon for Translator. Fixes #1465

Numix-Circle/48x48/apps/currency.svg, Numix-Circle/48x48/apps/keurocalc.svg
Pushed icon for Currency, issue #1466 (symlinked for KEuroCalc #1497):
Alternative:
If both are good I could use one for KEuroCalc.
Or just symlink KEuroCalc to the existing Grisbi icon.
=> Icon for Currency + symlink for KEuroCalc. Fixes #1466 , Fixes #1497

Numix-Circle/48x48/apps/kgeography.svg
Icon for KGeography. Fixes #1500
Pushed:
Alt:
=> Icon for KGeography. Fixes #1500

Numix-Circle/48x48/apps/cutemarked.svg
Icon for CuteMarkEd, issue #1490
Pushed icon:
Alternatives:
=> Icon for CuteMarkEd. Fixes #1490

Numix-Circle/48x48/apps/yagf.svg
Icon for YAGF, issue #1103
Or the lighter alternative:
=> Icon for YAGF. Fixes #1103

Numix-Circle/48x48/apps/notepadqq.svg
Icon for Notepadqq, issue #1537
Pushed:
Alt:
=> Icon for Notepadqq. Fixes #1537

Numix-Circle/48x48/apps/gnome-color-chooser.svg
Symlink to *preferences-color.svg*
=> Icon for GNOME Color Chooser (symlink). Fixes #1553

Numix-Circle/48x48/apps/openteacher.svg
Icon for OpenTeacher. Fixes #1558
Pushed:
Alternatives:
=> Icon for OpenTeacher. Fixes #1558

Numix-Circle/48x48/apps/cutegram.svg
Icon for Cutegram. Fixes #1581
=> Icon for Cutegram. Fixes #1581

Numix-Circle/48x48/apps/kphotoalbum.svg
Icon for KPhotoAlbum (symlink). Fixes #1595
Symbolic link to *fotowall.svg*
=> Icon for KPhotoAlbum (symlink). Fixes #1595

Numix-Circle/48x48/apps/gpa.svg
Icon for GPA (symlink). Fixes #1593
Symbolic link to *stock_keyring.svg*
=> Icon for GPA (symlink). Fixes #1593

Numix-Circle/48x48/apps/ezame.svg
Icon for Ezame. Fixes #1073
Symlink to existing *menu-editor.svg*
=> Icon for Ezame (symlink). Fixes #1073

Numix-Circle/48x48/apps/scidavis.svg
Symlink to the existing QtiPlot icon.
=> Icon for SciDAVis (symlink). Fixes #1571

Numix-Circle/48x48/apps/ufraw.svg
Icon for UFRaw. Fixes #1570
Pushed:
Alternatives:
=> Icon for UFRaw. Fixes #1570

Numix-Circle/48x48/apps/bovo.svg, Numix-Circle/48x48/apps/katomic.svg, Numix-Circle/48x48/apps/kbounce.svg, Numix-Circle/48x48/apps/kigo.svg, Numix-Circle/48x48/apps/kmahjongg.svg, Numix-Circle/48x48/apps/kmines.svg
Icons for several KDE games. Fixes #1578
Bovo
KAtomic
KBounce
Kigo
KMahjongg
KMines
symlink to *gnome-mines.svg*
=> Icons for several KDE games. Fixes #1578

Numix-Circle/48x48/apps/kapow.svg
Icon for Kapow. Fixes #1611
Symlink to *gnome-schedule.svg*
=> Icon for Kapow. Fixes #1611

Numix-Circle/48x48/apps/ktimetracker.svg
Icon for KTimeTracker(symlink). Fixes #1618
Symlink to *indicator-remindor.svg*
=> Icon for KTimeTracker(symlink). Fixes #1618

Numix-Circle/48x48/apps/fgfs.svg, Numix-Circle/48x48/apps/fgrun.svg
Added symlinks *fgfs.svg* and *fgrun.svg* (in case it isn't hardcoded on some distros).
See #1630
=> Symlinks for Flightgear

Numix-Circle/48x48/apps/epdfview.svg
Icon for ePDFViewer (symlink). Fixes #1638
Symlink to *qpdfview.svg*
=> Icon for ePDFViewer (symlink). Fixes #1638

Numix-Circle/48x48/apps/gnome-multi-writer.svg
Icon for MultiWriter. Fixes #1640
Pushed:
Alt:
=> Icon for MultiWriter. Fixes #1640

Numix-Circle/48x48/apps/LabPlot2.svg
Icon for LabPlot. Fixes #1643
symlink to *kmplot.svg*
=> Icon for LabPlot (symlink). Fixes #1643

Numix-Circle/48x48/apps/knetattach.svg
Icon for KNetAttach. Fixes #1645
Alt:
or simply a symlink to *remote-desktop.svg*
=> Icon for KNetAttach. Fixes #1645

Numix-Circle/48x48/apps/flowblade.svg
Icon for Flowblade. Fixes #1632 
Pushed:
Alt:
=> Icon for Flowblade. Fixes #1632

Numix-Circle/48x48/apps/foobnix.svg
=> Icon for Foobnix. Fixes #1652

Numix-Circle/48x48/apps/kolf.svg
=> Icon for Kolf. Fixes #1651

Numix-Circle/48x48/apps/kmetronome.svg
Icon for KMetronome (symlink). Fixes #1667
Symlink to *gtick.svg*
=> Icon for KMetronome (symlink). Fixes #1667

Numix-Circle/48x48/apps/gtklick.svg
Icon for gtklick (symlink). Fixes #1661
Symlink to *gtick.svg*
=> Icon for gtklick (symlink). Fixes #1661

Numix-Circle/48x48/apps/nomacs.svg
Icon for nomacs (symlink). Fixes #1635
Symlink to *kuickshow.svg*
=> Icon for nomacs (symlink). Fixes #1635

Numix-Circle/48x48/apps/rapid-photo-downloader.svg
Icon for Rapid Photo Downloader. Fixes #966
Pushed:
Alts:
=> Icon for Rapid Photo Downloader. Fixes #966

Numix-Circle/48x48/apps/jack-keyboard.svg
Icon for JACK keyboard. Fixes #1700
=> Icon for JACK keyboard

Numix-Circle/48x48/apps/pcb.svg
=> Icon for PCB Desinger (symlink). Fixes #1692

Numix-Circle/48x48/apps/JabRef-icon-48.svg, Numix-Circle/48x48/apps/TagTool.svg, Numix-Circle/48x48/apps/gtkpycad.svg
gtkpycad.svg --> pycad.svg
TagTool.svg --> audio-tag-tool.svg
JabRef-icon-48.svg --> jabref.svg
=> Added missing symlinks for PyCAD, JabRef and Audio Tag Tool

Numix-Circle/48x48/apps/digikam.svg
Made this icon for digiKam:
Replaces the current icon (symlink) which is also used for several screenshot/camera apps:
=> Enhanced icon for digiKam

Numix-Circle/48x48/apps/kollision.svg
Icon for Kollision. Fixes #1738
=> Icon for Kollision. Fixes #1738

Numix-Circle/48x48/apps/kmag.svg
=> Icon for KMag. Fixes #1744

Numix-Circle/48x48/apps/connectagram.svg
Icon for Connectagram. Fixes #1742
=> Icon for Connectagram. Fixes #1742

Numix-Circle/48x48/apps/kblackbox.svg, Numix-Circle/48x48/apps/kdiamond.svg
Icons for KDiamond and KBlackbox. Fixes #1750
=> Icons for KDiamond and KBlackbox. Fixes #1750

Numix-Circle/48x48/apps/geda-gschem.svg
Icon for gEDA Schematic Editor. Fixes #1752
Pushed:
Alt:
=> Icon for gEDA Schematic Editor. Fixes #1752

Numix-Circle/48x48/apps/kbreakout.svg
Icon for KBreakout. Fixes #1758
Pushed:
Alt:
=> Icon for KBreakout. Fixes #1758

Numix-Circle/48x48/apps/parcellite.svg
Icon for Parcellite. Fixes #1761
=> Icon for Parcellite. Fixes #1761

Numix-Circle/48x48/apps/gimagereader.svg
Icon for gImageReader. Fixes #1760
=> Icon for gImageReader. Fixes #1760

Numix-Circle/48x48/apps/gnoduino.svg
Icon for Gnoduino (symlink). Fixes #1768
Symlink to *arduino.svg*
=> Icon for Gnoduino (symlink). Fixes #1768

Numix-Circle/48x48/apps/gsmartcontrol.svg
Icon for GSmartControl. Fixes #1764
=> Icon for GSmartControl. Fixes #1764

Numix-Circle/48x48/apps/streamtuner.svg, Numix-Circle/48x48/apps/streamtuner2.svg
Icon for Streamtuner2 (symlink). Fixes #1781
Symlinks to *radio.svg*
=> Icon for Streamtuner2 (symlink)

Numix-Circle/48x48/apps/gufw.svg
GUFW icon enhancement: remove strokes, change colours.
Previous icon got not coherent red strokes:
I've removed the strokes and remodelled the icon changin colours:
I've used those colours cause they appear in the main menu:
=> GUFW icon enhancement

Numix-Circle/48x48/apps/latexdraw.svg
Icon for LaTeXDraw. Fixes #1817
=> Icon for LaTeXDraw

Numix-Circle/48x48/apps/sportstracker.svg
Icon for SportsTracker. Fixes #1828
Pushed:
Alt:
=> Icon for SportsTracker

Numix-Circle/48x48/apps/kompare.svg
Icon for Kompare, Fixes #1836 
+Added missing shadow and gradient to the new diffpdf icon.
=> Icon for Kompare, fixed diffpdf icon.

Numix-Circle/48x48/apps/shotcut.svg
Icon for Shotcut. Fixes #1840
Pushed:
Alt:
=> Icon for Shotcut

Numix-Circle/48x48/apps/tetzle.svg
Icon for Tetzle. Fixes #1864
Pushed:
Alt:
=> Icon for Tetzle

Numix-Circle/48x48/apps/diskmonitor.svg
Icon for Diskmonitor. Fixes #1883
Symlink to *gsmartcontrol.svg*
=> Icon for Diskmonitor (symlink)

Numix-Circle/48x48/apps/ksquares.svg
Fixes #1890
Symlink to a tetris clone chrome app icon
=> Icon for KSquares (symlink)

Numix-Circle/48x48/apps/gambitchess.svg
Icon for Gambit (symlink). Fixes #1894
Symlink to *knights.svg*
=> Icon for Gambit (symlink)

Numix-Circle/48x48/apps/zeegaree-lite.svg, Numix-Circle/48x48/apps/zeegaree.svg
Symlinks for Zeegaree. Fixes #945
Symlinks to *kronometer.svg*
Alternatively it could be linked to *indicator-remindor.svg*, *preferences-system-time.svg*, *pomidor.svg* or *gnome-clocks.svg*.
=> Symlinks for Zeegaree

Numix-Circle/48x48/apps/boomaga.svg
Icon for Boomaga. Fixes #1933
Alt:
=> Icon for Boomaga

Numix-Circle/48x48/apps/buzztrax.svg
Icon for Buzztrax. Fixes #1942
Alt:
=> Icon for Buzztrax

Numix-Circle/48x48/apps/kdf.svg, Numix-Circle/48x48/apps/kget.svg, Numix-Circle/48x48/apps/kwalletmanager.svg
Next batch of KDE app icons. Fixes #1946
KWalletmanager: symlink to *stock_keyring.svg*
KDiskFree: symlink to *disk-usage-analyzer.svg*
KGet:
=> Next batch of KDE app icons

Numix-Circle/48x48/apps/cirkuit.svg, Numix-Circle/48x48/apps/kdesvn.svg, Numix-Circle/48x48/apps/kfilereplace.svg, Numix-Circle/48x48/apps/kiten.svg, Numix-Circle/48x48/apps/kscd.svg, Numix-Circle/48x48/apps/kst.svg
Even more KDE stuff. Fixes #1959
+ Cirkuit
Symlink to *latexdraw.svg*
+ KDEsvn
+ KFileReplace
Symlink to *rename.svg*
+ Kiten
Symlink to *jiten.svg*
+ KsCD
Symlink to *goobox.svg*
+  KSt
=> Even more KDE stuff

Numix-Circle/48x48/apps/kaudiocreator.svg
Icon for KAudioCreator. Fixes #1964
=> Icon for KAudioCreator

Numix-Circle/48x48/apps/zanshin.svg
=> Icon for Zanshin

Numix-Circle/48x48/apps/gtg.svg, Numix-Circle/48x48/apps/musique.svg, Numix-Circle/48x48/apps/opensong.svg
The icons for Opensong and Musique (same design, recoloured)had their symbols misaligned.
Before:
After:
The GTG icon's symbols used a transparent color. Replaced it by the equivalent A255 colour.
=> Fixes for Opensong, Musique, GTG

Numix-Circle/48x48/apps/gpsprune.svg
Icon for gpsprune. Fixes #1977
=> Icon for gpsprune

Numix-Circle/48x48/apps/picsaw.svg
=> Icon for Picsaw

Numix-Circle/48x48/apps/klipper.svg
Symlink for Klipper. Fixes #1992
Symlink to *diodon.svg*
=> Symlink for Klipper

Numix-Circle/48x48/apps/umbrello.svg
Icon for Umbrello. Fixes #1994
Pushed:
Alt:
=> Icon for Umbrello

Numix-Circle/48x48/apps/fraqtive.svg
Icon for Fraqtive. Fixes #2001
=> Icon for Fraqtive. Fixes #2001

Numix-Circle/48x48/apps/.directory, Numix-Circle/48x48/apps/buddi.svg
Icon for Buddi. Fixes #2022
Pushed:
Alt:
=> Icon for Buddi. Fixes #2022

Numix-Circle/48x48/apps/rosegarden.svg
Icon for Rosegarden. Fixes #1090
Btw, some magnificent new icons by you lately @Foggalong :+1:
=> Icon for Rosegarden

Numix-Circle/48x48/apps/peazip.svg
=> Icon for PeaZip

Numix-Circle/48x48/apps/unity-launcherswitcher.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2037.
This icon takes `workspace-switcher-top-left.svg` as a starting point and then adapts the colours to the original icon while leaving the red colour the same.
=> Added unity-launcherswitcher.svg

Numix-Circle/48x48/apps/unsettings.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2036.
This is the icon in Inkscape:
and here showing in the Ubuntu 14.10 system settings in the upper right:
I am wondering though: for some reason, the drop shadow of the center part is not displayed properly with the Ubuntu default image viewer eog:
and on GitHub "View", the center part is not showing at all, only the "U". And the file size appears to be a bit bigger than usual. Could you point me to what might be wrong here, if s.th. is wrong? Thanks!
=> Added unsettings.svg

Numix-Circle/48x48/apps/unsettings.svg
Coming back to https://github.com/numixproject/numix-icon-theme-circle/pull/2052, here is the same icon after cleaning up the "duplicate linear gradient stop color" by deleting and re-creating the linear gradient.
=> Corrected unsettings.svg

Numix-Circle/48x48/apps/gxine.svg
Fixes #2059
Symlink to [xine.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/xine.svg)
=> Symlink for gxine

Numix-Circle/48x48/apps/regexxer.svg
Symlink to [search.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/search.svg) for Regexxer. Fixes #2090
=> Symlink for Regexxer

Numix-Circle/48x48/apps/mkvtoolnix-gui.svg
There is a new icon name in the package desktop file. I added a symlink.
=> Icon for MKVToolNix on Arch Linux

Numix-Circle/48x48/apps/pogo.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2076.
=> Added icon for Pogo

Numix-Circle/48x48/apps/pytrainer.svg
Fixes #2126
Symlink to [sportstracker.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/sportstracker.svg)
Alt:
=> Icon for Pytrainer

Numix-Circle/48x48/apps/glogg.svg
Using the icon line from the repo, see #2302.
Symlink to ``gpk-log.svg`` as the ``logview.svg`` design is used quite often already.
=> Symlink in glogg

Numix-Circle/48x48/apps/weather-clear.svg
Indicator-weather uses this icon to display the weather condictions in the panel.If this icon (which is clearly a status icon is present in circle) the circular icon is used instead of the status icon -> Remove it, and blame the program that uses an status icon as app icon
=> Removes weather-clear.svg from circle

Numix-Circle/48x48/apps/merkaartor.svg
An Open Street Map editor
http://wiki.openstreetmap.org/wiki/Merkaartor
Icon=merkaartor
=> Symlink for Merkaartor

Numix-Circle/48x48/apps/brackets.svg
The brackets weren't equally wide.
Before:
After:
Or better this way or with a shadow?
=> Brackets alignment fix

Numix-Circle/48x48/apps/girl.svg
=> Icon for GNOME Internet Radio Locator. Fixes #2501

Numix-Circle/48x48/apps/gnome-todo.svg
New app for GNOME 3.18.
https://wiki.gnome.org/Apps/Todo
Icon=gnome-todo
It's the [Tasque](https://wiki.gnome.org/Apps/Tasque) icon recoloured so that's what I did.
=> Icon for GNOME To Do

Numix-Circle/48x48/apps/qwinff.svg
FFmpeg media file converting GUI
http://qwinff.github.io/
Icon=qwinff
Added missing gradient to *winff.svg*.
=> Icon for QWinFF, fixes for WinFF

Numix-Circle/48x48/apps/unity-editor-icon.svg, Numix-Circle/48x48/apps/unity-monodevelop.svg
* Background gradient colour fixed in unity-editor-icon.svg ( #2505 )
* New icon: unity-monodevelop.svg
=> Unity Editor fix and Unity Monodevelop new icon

Numix-Circle/48x48/apps/maxima.svg
Created a symlink to wxMaxima icon that already existed. These interfaces are different but we can use same icon. 
In this case it is not **hardcoded**.
=> Maxima X interface icon

Numix-Circle/48x48/apps/mediaelch.svg
On Arch, with the latest version of MediaElch and using Hardcode-Fixer, the icon doesn't show up.
It needs to be named mediaelch instead of MediaElch, so I made a symlink to it.
=> Added symlink for MediaElch

Numix-Circle/48x48/apps/butter.svg
Popcorn Time successor
http://butterproject.org/
Original icon:
=> Symlink for Butter

Numix-Circle/48x48/apps/tkpacman-icon.svg, Numix-Circle/48x48/apps/tkpacman.svg, Numix-Circle/48x48/apps/yumex-dnf.svg, Numix-Circle/48x48/apps/yumex.svg
GUI for the pacman package manager
http://sourceforge.net/projects/tkpacman/
tkpacman.desktop
Icon=/usr/share/tkpacman/icons/tkpacman-icon.png
Furthermore I've edited tje yumex symlinks such that the yumex icon is more close to the original icon and looks distinct from the icon used by gnome-packagekit.
=> Tkpacman symlinks, yumex symlink enhancement

Numix-Circle/48x48/apps/jasp-desktop.svg
statistical package
https://jasp-stats.org/
Icon0jasp-desktop
**Alt (subtle non-drop non-Numixy shadow below the circles):**
=> Icon for Jasp Desktop

Numix-Circle/48x48/apps/keepassx2.svg
KeePassX 2 is out and for Arch Linux the icon name is updated.
=> Added keepassx2 link.

Numix-Circle/48x48/apps/goa-account.svg
I created the live icon from the numix "live" icon and the background of the microsoft icon. It probably needs a shadow added. I created it using inkscape & `svgo --pretty --disable=collapseGroups,convertPathData live.svg`
Otherwise, I just set up the appropriate symlinks.
=> Add goa-account icons

Numix-Circle/48x48/apps/skychart.svg
I've had this resting on my disk for a while:
Diverging from the guidelines but recognisable and small sizes and true to the original icon:
Alt with shadows:
Maybe a bigger meteor?
=> Distinct icon for Sky Chart

Numix-Circle/48x48/apps/plasmadiscover.svg, Numix-Circle/48x48/apps/spectacle.svg
They got a new screenshot app and *Moun Discover* is now just *Discover*.
=> Symlinks for KDE apps

Numix-Circle/48x48/apps/ltspice.svg
I recently created icon for LTSpice, a electronics simulation software.
It doesn't run on Linux, but You can easily use it in WINE, so I thought You may want to consider adding its icon to the set.
This is my Icon:
*(Again, sorry for that brown backround)*
I tried to follow guideline, but if something's wrong, let me know, I'm willing to fix it. ;)
=> Icon for LTSpice

Numix-Circle/48x48/apps/xed.svg, Numix-Circle/48x48/apps/xplayer.svg, Numix-Circle/48x48/apps/xreader.svg, Numix-Circle/48x48/apps/xviewer.svg
Looks like the Mint guys forked some more GNOME apps because of not liking the header bars
http://segfault.linuxmint.com/2016/02/the-first-two-x-apps-are-ready/
https://github.com/linuxmint/xed
https://github.com/linuxmint/xviewer
https://github.com/linuxmint/xplayer
https://github.com/linuxmint/xreader
=> Symlinks for X-Apps

Numix-Circle/48x48/apps/org.gnome.Photos.svg, Numix-Circle/48x48/apps/org.gnome.Totem.svg
Looks like finally all GNOME apps will undergo the ``org.gnome`` treatment.
From what I heard it is neccessary for setting up xdg-bundles for some reason.
=> Symlinks for GNOME Photos and Totem

Numix-Circle/48x48/apps/runescape.svg
Fixes #2855
Runescape Linux/Unix Client repo: https://github.com/HikariKnight/rsu-client/
Original:
Pushed:
The icon line in the original .desktop is hardcoded: `Icon=/opt/runescape/share/img/runescape.png`
=> Icon for RuneScape
