numixproject/circle-core

Numix-Circle/48x48/apps/trelby.svg
Icon for Trelby, issue #1410
Rotated (pushed):
or non-rotated:
=> Icon for Trelby. Fixes #1410

Numix-Circle/48x48/apps/go-for-it.svg
Icon for Go For It, issue #1434
=> Icon for Go For It. Fixes #1434

Numix-Circle/48x48/apps/entangle.svg
Icon for Entangle, issue #1432
=> Icon for Entangle. Fixes #1432

Numix-Circle/48x48/apps/qtox.svg
=> Icon for qTox. Fixes #1445

Numix-Circle/48x48/apps/utox.svg
=> Icon for uTox. Fixes #1413

Numix-Circle/48x48/apps/fritzing.svg
Symlink for Fritzing. Fixes issue #1478
=> Symlink for Fritzing. Fixes #1478

Numix-Circle/48x48/apps/aquemu_48x48.svg
=> Icon for AQEMU. Fixes #1469

Numix-Circle/48x48/apps/pokerth.svg
=> Icon for PokerTH. Fixes #1468

Numix-Circle/48x48/apps/thg_logo.svg
=> TortoiseHG icon

Numix-Circle/48x48/apps/okteta.svg
Icon for Okteta, issue #1220.
Symlink to bless-48x48.svg
=> Icon for Okteta (symlink). Fixes #1220

Numix-Circle/48x48/apps/MediathekView.svg, Numix-Circle/48x48/apps/setBfree.svg
=> Added symlinks for MediathekView and setBfree

Numix-Circle/48x48/apps/multibit.svg
Created a symlink to  existing *bitcoin.svg*
=> Icon for MultiBit. Fixes #1456

Numix-Circle/48x48/apps/gnash.svg
=> Icon for Gnash. Fixes #1450

Numix-Circle/48x48/apps/jedit.svg
=> Icon for jEdit. Fixes #1467

Numix-Circle/48x48/apps/nasc.svg
=> Icon for NaSC. Fixes #1486

Numix-Circle/48x48/apps/denemo.svg
=> Icon for Denemo. Fixes #1019

Numix-Circle/48x48/apps/kalgebra.svg
=> Icon for KAlgebra. Fixes #1501

Numix-Circle/48x48/apps/qelectrotech.svg
=> QElectroTech icon: Fixed alignment+size

Numix-Circle/48x48/apps/taxi.svg
=> Icon for Taxi. Fixes #1515

Numix-Circle/48x48/apps/performous.svg
=> Performous Icon

Numix-Circle/48x48/apps/kwordquiz.svg
Icon for KWordQuiz. Fixes #1531
=> Icon for KWordQuiz. Fixes #1531

Numix-Circle/48x48/apps/cantor.svg
Icon for Cantor. Fixes issue #1527
Pushed:
Alt:
=> Icon for Cantor. Fixes #1527

Numix-Circle/48x48/apps/kig.svg
=> Icon for Kig. Fixes #1529

Numix-Circle/48x48/apps/cherrytree.svg
Icon for Cherrytree. Fixes #1357
=> Icon for Cherrytree. Fixes #1357

Numix-Circle/48x48/apps/natronIcon256_linux.svg
=> Natron Icon

Numix-Circle/48x48/apps/translator.svg
Now in colourful colours :rainbow:
See #1496 for the old one.
=> Translator icon - colourful bubbles

Numix-Circle/48x48/apps/kdevelop.svg
Icon for KDevelop. Fixes #1550
=> Icon for KDevelop. Fixes #1550

Numix-Circle/48x48/apps/power-installer.svg
Icon for Power Installer. Fixes #1506
Pushed:
Alt:
=> Icon for Power Installer. Fixes #1506

Numix-Circle/48x48/apps/nuvolaplayer3.svg
Created symbolic link nuvolaplayer3.svg to nuvolaplayer.svg
=> Icon for Nuvola Player 3

Numix-Circle/48x48/apps/kruler.svg
Icon for KRuler. Fixes #1587.
Symlink to existing *screenruler.svg*
=> Icon for KRuler. Fixes #1587

Numix-Circle/48x48/apps/peg-e.svg
=> Icon for Peg-E. Fixes #1610

Numix-Circle/48x48/apps/gottet.svg
Icon for Gottet. Fixes #1609
Symlink to *ltris.svg*
=> Icon for Gottet. Fixes #1609

Numix-Circle/48x48/apps/steam_icon_250900.svg
Binding of Isaac icon, closes #1411
=> Binding of Isaac icon

Numix-Circle/48x48/apps/steam_icon_233450.svg
Prison Architect icon. Closes #1563
=> Prison Architect icon

Numix-Circle/48x48/apps/i-nex-128.svg
Icon for I-Nex, pushed as *i-nex-128.svg* Fixes #1010
=> Icon for I-Nex. Fixes #1010

Numix-Circle/48x48/apps/lokalize.svg
Icon for Lokalize (symlink). Fixes #1619
Symlink to *preferences-desktop-locale.svg*
=> Icon for Lokalize(symlink). Fixes #1619

Numix-Circle/48x48/apps/rkward.svg
Icon for RKWard. Fixes #1644
Just the R icon recoloured
=> Icon for RKWard. Fixes #1644

Numix-Circle/48x48/apps/baobab.svg, Numix-Circle/48x48/apps/pspp.svg
Fixed odd shape and misalignments
Before:
After:
=> Fixes for Baobab and PSPP

Numix-Circle/48x48/apps/linthesia.svg
Icon for Linthesia (symlink). Fixes #1668
Symlink to *vmpk.svg*
=> Icon for Linthesia (symlink). Fixes #1668

Numix-Circle/48x48/apps/steam_icon_236850.svg
Europa Universalis IV, closes #1665
=> Europa Universalis IV icon

Numix-Circle/48x48/apps/steam_icon_204300.svg
=> Awesomenauts icon (Steam version)

Numix-Circle/48x48/apps/linphone.svg
=> Icon for Linphone. Fixes #977

Numix-Circle/48x48/apps/applications-accessories.svg, Numix-Circle/48x48/apps/applications-development.svg, Numix-Circle/48x48/apps/applications-graphics.svg, Numix-Circle/48x48/apps/applications-multimedia.svg, Numix-Circle/48x48/apps/applications-office.svg
Symlinks Cinnamon Applications fix, closes #1580.
I think that chosen icons are right, what do you think about it?
=> Symlinks Cinnamon fix

Numix-Circle/48x48/apps/linphone.svg
=> Linphone icon fix.

Numix-Circle/48x48/apps/valentina.svg
Icon for Valentina. Fixes #1704
=> Icon for Valentina

Numix-Circle/48x48/apps/goobox.svg
=> Icon for Goobox. Fixes #1696

Numix-Circle/48x48/apps/LinSSID.svg, Numix-Circle/48x48/apps/linssid.svg
LinSSID icon, fixes #1313
Any suggestions?
=> LinSSID icon

Numix-Circle/48x48/apps/web-delicious.svg
=> Added Delicious (delicious.com) icon

Numix-Circle/48x48/apps/meandmyshadow.svg
Icon for Me and My Shadow. Fixes #1591
=> Icon for Me and My Shadow. Fixes 1591

Numix-Circle/48x48/apps/iViewer.svg
=> iViewer icon

Numix-Circle/48x48/apps/mundus.svg
=> Mundus icon

Numix-Circle/48x48/apps/openlugaru.svg
OpenLugaru Icon, fixes #1057
What do you think about it? Any suggestion?
=> OpenLugaru Icon

Numix-Circle/48x48/apps/openxcom.svg
=> OpenXCOM icon

Numix-Circle/48x48/apps/steam_icon_293780.svg
Crawl icon, closes #1069
Pushed one:
Alternative:
_Note: First one #1040_
=> Crawl icon

Numix-Circle/48x48/apps/steam_icon_239030.svg
Papers, Please icon, closes #937
_Note: Second one #1040_
=> Papers, Please icon

Numix-Circle/48x48/apps/p7zip.svg
Sorry, I forgot to mention the "p7zip" on issue #1716
GenericName=7-Zip File Manager
Icon=p7zip
=> Additional fix for #1716

Numix-Circle/48x48/apps/epsxe.svg
=> Icon for ePSXe. Fixes #1688

Numix-Circle/48x48/apps/p7zip.svg
Reverts numixproject/numix-icon-theme-circle#1721
=> Revert "Additional fix for #1716"

Numix-Circle/48x48/apps/p7zip.svg
=> change p7zip.svg link to 7zip.svg

Numix-Circle/48x48/apps/CMakeSetup.svg
=> Symlink for new CMake launcher.

Numix-Circle/48x48/apps/httraqt.svg
Symlink for HTTraQt. Fixes #1518
=> Symlink for HTTraQt. Fixes #1518

Numix-Circle/48x48/apps/bareftp.svg
=> Icon for bareftp. Fixes #1552

Numix-Circle/48x48/apps/securecrt.svg, Numix-Circle/48x48/apps/securecrt_64.svg
=> SecureCRT icon

Numix-Circle/48x48/apps/tanglet.svg
=> Icon for Tanglet. Fixes #1743

Numix-Circle/48x48/apps/scribus.svg
=> Scribus icon fixes

Numix-Circle/48x48/apps/foobillardplus.svg
Icon for Foobillard (symlink). Fixes #1753
=> Icon for Foobillard (symlink). Fixes #1753

Numix-Circle/48x48/apps/gnome-genius.svg
Icon for Genius (symlink). Fixes #1765
Symlink to *nasc.svg*
=> Icon for Genius (symlink). Fixes #1765

Numix-Circle/48x48/apps/autocad.svg, Numix-Circle/48x48/apps/chrome-dcjeclnkejmbepoibfnamioojinoopln-Default.svg
Autocad 360 icon, closes #990 
--------------------------------------------------
Suggestions?
=> Autocad 360 icon

Numix-Circle/48x48/apps/steam_icon_22120.svg, Numix-Circle/48x48/apps/steam_icon_22140.svg, Numix-Circle/48x48/apps/steam_icon_22180.svg
Penumbra Series - closes #1683, closes #1684, closes #1682
_Overture:_
_Black Plague:_
_Requiem:_
=> Penumbra Icons

Numix-Circle/48x48/apps/chrome-hjbljnpdahefgnopeohlaeohgkiidnoe-Default.svg
A smaller inner-circle made it look too much like a record so I made it square. I think it's supposed to resemble a television..
Let me know if the size ratios are ok.
Thanks!
=> add Allcast Receiver Chrome app icon

Numix-Circle/48x48/apps/valama.svg
Icon for Valama (symlink). Fixes #1786
=> Icon for Valama

Numix-Circle/48x48/apps/QtProject-designer.svg
For icon line *QtProject-designer*
=> Additional symlink for Qt Designer

Numix-Circle/48x48/apps/freeminer.svg
=> Added freeminer icon

Numix-Circle/48x48/apps/scudcloud.svg
=> Added scudcloud

Numix-Circle/48x48/apps/qstardict.svg
Icon for QStarDict (symlink). Fixes #1816
=> Icon for QStarDict (symlink)

Numix-Circle/48x48/apps/oracle-sqldeveloper.svg
=> Oracle SQL Developer icon enhancement

Numix-Circle/48x48/apps/kdiff3.svg
=> Icon for KDiff3

Numix-Circle/48x48/apps/anoise.svg
=> Icon for anoise, fixes #1842

Numix-Circle/48x48/apps/gnome-books.svg
=> GNOME Books icon enhancement

Numix-Circle/48x48/apps/simsu.svg
=> Icon for Simsu

Numix-Circle/48x48/apps/paperwork.svg
Icon for Paperwork. Fixes #1868
=> Icon for Paperwork

Numix-Circle/48x48/apps/atomix-icon.svg
=> Icon for Atomix. Fixes #1870

Numix-Circle/48x48/apps/ocrfeeder.svg
Icon for OCRFeeder. Fixes #1872
=> Icon for OCRFeeder

Numix-Circle/48x48/apps/frogr.svg
=> Icon for Frogr

Numix-Circle/48x48/apps/glabels-3.0.svg, Numix-Circle/48x48/apps/glabels.svg
=> Icon for gLabels

Numix-Circle/48x48/apps/gnubik.svg, Numix-Circle/48x48/apps/kubrick.svg, Numix-Circle/48x48/apps/pybik.svg
Icon for cube games. Fixes #1881
=> Icon for cube games

Numix-Circle/48x48/apps/granatier.svg
Icon for Granatier. Fixes #1887
=> Icon for Granatier

Numix-Circle/48x48/apps/skrooge.svg
=> Icon for Skrooge

Numix-Circle/48x48/apps/alleyoop.svg
Icon for Alleyoop. Fixes #1916
=> Icon for Alleyoop

Numix-Circle/48x48/apps/skychart.svg
Symlink to *stellarium.svg* for Skychart. Fixes #1922
=> Symlink for Skychart

Numix-Circle/48x48/apps/killbots.svg
Icon for Killbots. Fixes #1931
=> Icon for Killbots

Numix-Circle/48x48/apps/gdiskdump.svg
=> Symlink for Gdiskdump

Numix-Circle/48x48/apps/dreamchess.svg
=> Symlink for dreamchess

Numix-Circle/48x48/apps/klickety.svg, Numix-Circle/48x48/apps/picmi.svg
Icons for KLickety and Picmi. Fixes #1948
=> Icons for Klickety and Picmi

Numix-Circle/48x48/apps/drgeo.svg, Numix-Circle/48x48/apps/drgeo2.svg
=> Icon for DrGeo

Numix-Circle/48x48/apps/kmouth.svg
Speech synthesizer frontend
https://www.kde.org/applications/utilities/kmouth/
Symlink to *espeak-gui.svg*
=> Symlink for Kmouth

Numix-Circle/48x48/apps/krdc.svg
Remote dektop client
https://www.kde.org/applications/internet/krdc/
Symlink to *remote-desktop.svg*
=> Symlink for KRDC

Numix-Circle/48x48/apps/ancestris.svg
=> Symlink for Ancestris. Fixes #1973

Numix-Circle/48x48/apps/glogic.svg, Numix-Circle/48x48/apps/klogic4.svg
=> Symlink for gLogic and KLogic. Fixes #1975

Numix-Circle/48x48/apps/gnome-oregano.svg, Numix-Circle/48x48/apps/oregano.svg
=> Icon for Oregano

Numix-Circle/48x48/apps/tasque.svg
=> Icon for Tasque

Numix-Circle/48x48/apps/pymol.svg
=> Icon for PyMOL

Numix-Circle/48x48/apps/camera-app.svg
=> Symlink for Camera app

Numix-Circle/48x48/apps/fgx.svg
=> Symlink for Fgx

Numix-Circle/48x48/apps/mandelbulber.svg
=> Fixes #1202

Numix-Circle/48x48/apps/steam_icon_332970.svg
Storm United, closes #1999
I am not sure about this one, any suggestion?
=> Storm United Icon

Numix-Circle/48x48/apps/samplv1.svg
=> Icon for samplv1. Fixes #2008

Numix-Circle/48x48/apps/visualparadigm.svg
=> Fixes #2011

Numix-Circle/48x48/apps/.directory, Numix-Circle/48x48/apps/xboard.svg
Symlink for Xboard. Fixes #2024
=> Symlink for Xboard. Fixes #2024

Numix-Circle/48x48/apps/gnome-pomodoro.svg
=> Symlink for Gnome Pomodoro

Numix-Circle/48x48/apps/timeline.svg
=> Icon for Timeline

Numix-Circle/48x48/apps/kgoldrunner.svg
=> Icon for KGoldrunner

Numix-Circle/48x48/apps/bomber.svg, Numix-Circle/48x48/apps/ksirk.svg
=> Icons for Bomber and KSirK

Numix-Circle/48x48/apps/rocs.svg
=> Icon for Rocs

Numix-Circle/48x48/apps/kdesnake.svg
Removed duplicative baseplate leftover which resulted in an outline.
=> kdesnake fix

Numix-Circle/48x48/apps/dianara.svg
=> Icon for Dianara

Numix-Circle/48x48/apps/visualstudiocode.svg
#2041 (everything aligned to grid :)
=> Fixes #2041

Numix-Circle/48x48/apps/edgar.svg
Icon for The Legend of Edgar. Fixes #2073
=> Icon for The Legend of Edgar

Numix-Circle/48x48/apps/fillets-ng.svg
=> Icon for Fillets NG

Numix-Circle/48x48/apps/blam.svg
=> Icon for Blam. Fixes #2092

Numix-Circle/48x48/apps/trojita.svg
=> Icon for Trojita

Numix-Circle/48x48/apps/taskcoach.svg
Fixes #2089
Took the original zanshin icon.
=> Icon for Taskcoach

Numix-Circle/48x48/apps/gtk-gnutella.svg
=> Icon for GTK-Gnutella

Numix-Circle/48x48/apps/universalindentgui.svg
=> Icon for UniversalIndentGUI

Numix-Circle/48x48/apps/phototonic.svg
=> Icon for Phototonic

Numix-Circle/48x48/apps/tvbrowser.svg
=> Icon for TV Browser

Numix-Circle/48x48/apps/Ardour-Ardour_4.0.0.svg
=> Symlink for Ardour. Fixes #2112

Numix-Circle/48x48/apps/qstopmotion.svg
=> Icon for qStopMotion

Numix-Circle/48x48/apps/qmidiarp.svg
=> Icon for QMidiArp

Numix-Circle/48x48/apps/passaffe.svg
=> Icon for Pasaffe

Numix-Circle/48x48/apps/actionaz.svg
=> Icon for Actionaz

Numix-Circle/48x48/apps/sgt-blackbox.svg, Numix-Circle/48x48/apps/sgt-net.svg, Numix-Circle/48x48/apps/sgt-pegs.svg
More symlinks for "Simon Tatham's portable puzzle collection" games.
=> sgt-puzzles symlinks

Numix-Circle/48x48/apps/xcircuit.svg
=> Icon for XCircuit

Numix-Circle/48x48/apps/geda-gattrib.svg
=> Icon for gattrib

Numix-Circle/48x48/apps/terasology.svg
Fixes #2145
Symlink to [freeminer.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/freeminer.svg)
=> Symlink for Terasology

Numix-Circle/48x48/apps/nmm_qt_client.svg
Fixes #2152
Symlink to [kapt.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/kpat.svg)
=> Symlink for NetMauMau

Numix-Circle/48x48/apps/kshutdown.svg
=> Icon for KShutdown

Numix-Circle/48x48/apps/quake-armagon.svg, Numix-Circle/48x48/apps/quake-dissolution.svg
made up some icons for the quake expansion packs. if there is any way to improve them, just tell me
fixes #2153 and #2154
=> Icon for Quake expansion packs. Fixes #2153 and #2154

Numix-Circle/48x48/apps/areca.svg, Numix-Circle/48x48/apps/areca_72x72.svg
=> Icon for Areca

Numix-Circle/48x48/apps/yumex-dnf.svg
Fixes #2173
Symlink to [yumex.svg](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/yumex.svg)
=> Symlink for yumex-dnf

Numix-Circle/48x48/apps/preferences-desktop-wallpaper.svg
Changed in icon preferences-desktop-wallpaper.svg the colour of the foot of the monitor to be consistent with preferences-desktop-display.svg.
=> Change colour of foot

Numix-Circle/48x48/apps/tintii.svg
=> Icon for Tintii

Numix-Circle/48x48/apps/drumkv1.svg, Numix-Circle/48x48/apps/synthv1.svg
=> Missing icons for the v1 suite. Fixes #2181

Numix-Circle/48x48/apps/gnome-pie.svg
=> Icon for GNOME Pie

Numix-Circle/48x48/apps/billiards.svg
=> Symlink for Billiards

Numix-Circle/48x48/apps/gpx-viewer.svg
=> Symlink for GPX Viewer

Numix-Circle/48x48/apps/gogui.svg
=> Symlink for GoGui. Fixes #2192

Numix-Circle/48x48/apps/gtimelog.svg
=> Symlink for gtimelog

Numix-Circle/48x48/apps/ballerburg.svg
=> Icon for Ballerburg SDL

Numix-Circle/48x48/apps/rtcw.svg, Numix-Circle/48x48/apps/wolfenstein.svg
Did up an icon for some of the wolfenstein games. any issues, and ill get on a fix for it
=> Icon for Wolfenstein games

Numix-Circle/48x48/apps/apx.svg
=> Icon for APX

Numix-Circle/48x48/apps/oStorybook-icon.svg, Numix-Circle/48x48/apps/ostorybook.svg
=> Icon for oStorybook

Numix-Circle/48x48/apps/flaw.svg
=> Icon for Flaw

Numix-Circle/48x48/apps/sayonara.svg
=> Icon for Sayanora

Numix-Circle/48x48/apps/gonvert.svg
=> Icon for Gonvert

Numix-Circle/48x48/apps/pybliographic.svg
=> Symlink for Pybliographer

Numix-Circle/48x48/apps/shadowsocks-qt5.svg
=> Icon for Shadowsocks GUI

Numix-Circle/48x48/apps/liteide.svg
=> Icon for LiteIDE

Numix-Circle/48x48/apps/urbanlightscape.svg
=> Icon for Urban Lightscape

Numix-Circle/48x48/apps/chocolate-setup.svg
Now a proper symlink for this issue :D
=> Symlink for Chocolate Doom Setup. Fixes #2228

Numix-Circle/48x48/apps/ipscan.svg
=> Icon for Angry IP. Fixes #2233

Numix-Circle/48x48/apps/wolfenstein-the-new-order.svg
Resubmitted the pull request @Foggalong , this one is a lot more clean.
=> Icon for Wolfenstein: The New Order

Numix-Circle/48x48/apps/zandronum.svg
i think this is finally PR ready after a bunch of tweaking the backplate colour
=> Icon for Zandronum

Numix-Circle/48x48/apps/doomseeker.svg
should fix the remainder of the zandronum install :>
=> Icon for Doomseeker

Numix-Circle/48x48/apps/pumpa.svg
Icon for pumpa (https://pumpa.branchable.com/), a pump.io client.
=> Icon for pumpa

Numix-Circle/48x48/apps/ecwolf.svg, Numix-Circle/48x48/apps/wolf4sdl.svg
should fix 2 issues for the two Wolfenstein 3D engines currently in the repos
=> Wolfenstein 3D icon

Numix-Circle/48x48/apps/gnome-video-arcade.svg
Here ya go Foggy. A beautiful icon for GNOME Video Arcade!
=> Icon for GNOME Video Arcade

Numix-Circle/48x48/apps/gcleaner.svg
=> Icon for GCleaner

Numix-Circle/48x48/apps/eid-viewer.svg
An icon for eID Viewer, an electronic identity card reader.
=> Icon for eID Viewer

Numix-Circle/48x48/apps/lenmus.svg
=> Icon for Lenmus

Numix-Circle/48x48/apps/ascii-design.svg
=> Icon for Ascii Design

Numix-Circle/48x48/apps/icono_rakarrack_128x128.svg, Numix-Circle/48x48/apps/rakarrack.svg
=> Icon for Rakarrack

Numix-Circle/48x48/apps/freechartgeany.svg
=> Icon for Free Chart Geany

Numix-Circle/48x48/apps/prefixsuffix.svg
Fixes #2337
Symlink to ``rename.svg``
=> Symlink for Prefixsuffix

Numix-Circle/48x48/apps/tresorit.svg
A new PR for the icon for Tresorit.
=> Icon for Tresorit

Numix-Circle/48x48/apps/keepnote.svg
Used the background from Steam/DeadBeef, if I need to change it (as those are 2 popular apps) then let me know.  Tried to repliacte [KeepNote icon from their website](http://keepnote.org/images/keepnote-logo.png).
=> Added icon for KeepNote Note taking software

Numix-Circle/48x48/apps/drumstick.svg
The new drumstick icon is designed after the original one.
=> added drumstick icon

Numix-Circle/48x48/apps/cool-retro-term.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2333.
=> Added cool-retro-term.svg

Numix-Circle/48x48/apps/sun-java-jre8.svg, Numix-Circle/48x48/apps/sun-javaws-jre8.svg, Numix-Circle/48x48/apps/sun-jcontrol-jre8.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2359.
=> Added symlinks for jre8

Numix-Circle/48x48/apps/fontmatrix.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2355.
=> Added fontmatrix.svg

Numix-Circle/48x48/apps/laby.svg
=> Icon for Laby

Numix-Circle/48x48/apps/starcal2.svg
International calendar
https://github.com/ilius/starcal
Icon=starcal2
=> Symlink for Starcal

Numix-Circle/48x48/apps/steam_icon_300.svg
Easy fix for a game in Valves catalog :)
=> Symlink for Day Of Defeat: Source.

Numix-Circle/48x48/apps/enigma.svg
Puzzle game
http://www.nongnu.org/enigma/
**Pushed Numix Circle icon:**
=> Icon for Enigma

Numix-Circle/48x48/apps/ngraph.svg
Another graphing app
http://sourceforge.net/projects/ngraph-gtk/?source=directory
Icon=ngraph
Symlink to [grace.svg](https://github.com/numixproject/numix-icon-theme-circle/tree/master/Numix-Circle/48x48/apps/grace.svg)
=> Symlink for Ngraph-gtk

Numix-Circle/48x48/apps/l3afpad.svg
=> Symlink for l3afpad

Numix-Circle/48x48/apps/jskat.svg
Skat card game
http://www.jskat.org/index.html
Icon=jskat
**Pushed Numix icon:**
=> Icon for JSkat + kpat.svg fix

Numix-Circle/48x48/apps/galois.svg
Falling blocks game
http://www.nongnu.org/galois/
Icon=galois
**Pushed Numix icon:**
=> Icon for Galois

Numix-Circle/48x48/apps/web-pocketcaster.svg
I couldn't find some kind of "formal process" for creating/contributing icons, so apologies if I'm doing it all wrong.
Webstore page here: https://chrome.google.com/webstore/detail/pocketcaster/jmlelgnlpdinbjemiclfmgcpbpdjlhff
=> Add PocketCaster Icon

Numix-Circle/48x48/apps/multibit-hd.svg
Created a symlink to existing bitcoin.svg
=> Icon (symlink) for Multibit HD. Issue #2426

Numix-Circle/48x48/apps/pentobi.svg
A board game
http://sourceforge.net/projects/pentobi/
Icon=pentobi
More 3Dish alt:
=> Icon for Pentobi

Numix-Circle/48x48/apps/steam_icon_287980.svg
Added the missing baseplate gradient, removed remnants of old design, fixed librsvg outline.
=> Mini Metro fixes

Numix-Circle/48x48/bombono-dvd.svg
=> add asymlink for bombono-dvd

Numix-Circle/48x48/apps/gtk-youtube-viewer.svg
Lightweight youtube app
https://github.com/trizen/youtube-viewer
Icon=gtk-youtube-viewer
=> Symlink for gtk-youtube-viewer

Numix-Circle/48x48/apps/steam_icon_286690.svg, Numix-Circle/48x48/apps/steam_icon_287390.svg, Numix-Circle/48x48/apps/steam_icon_43110.svg, Numix-Circle/48x48/apps/steam_icon_43160.svg
=> Icons/Symlinks for Metro series

Numix-Circle/48x48/apps/wxmedit.svg
Text/Hex Editor
https://github.com/hltj/wxMEdit
wxmedit.desktop
Icon=/usr/share/pixmaps/wxmedit.png
=> Icon for wxMEdit

Numix-Circle/48x48/apps/eid-viewer.svg
Small alignment fixes, cleanup, contrast enhancement
=> Subtle fixes for eid-viewer

Numix-Circle/48x48/apps/qjackctl.svg
=> QJackCtl fixes

Numix-Circle/48x48/apps/jmol-icon.svg
=> Icon for Jmol

Numix-Circle/48x48/apps/gCAD3D.svg, Numix-Circle/48x48/apps/gcad3d.svg
http://www.gcad3d.org/
Original icon:
gCAD3D.desktop
Icon=/usr/share/gcad3d/icons/gCAD3D.xpm
=> Icon for gCAD3D

Numix-Circle/48x48/apps/go-today.svg
=> Removed go-today

Numix-Circle/48x48/apps/gnome-balsa.svg, Numix-Circle/48x48/apps/gnome-balsa2.svg
mail client
https://git.gnome.org/browse/balsa
Icon=gnome-balsa2
=> Symlink for Balsa

Numix-Circle/48x48/apps/ue4editor.svg
Unreal 4 Editor icon. Closes #2276
Hi there, long time without making an icon so please check if all is right. :wink:
=> Unreal 4 Editor icon

Numix-Circle/48x48/apps/ring.svg
FLOSS video communication software, SFLPhone successor.
http://ring.cx/
=> Icon for Ring

Numix-Circle/48x48/apps/steam_icon_238320.svg
=> Outlast icon (Steam)

Numix-Circle/48x48/apps/steam_icon_231430.svg
Company of Heroes 2 icon
**SteamID:** _231430_
=> Company of Heroes 2 icon (Steam)

Numix-Circle/48x48/apps/steam_icon_302610.svg
Boson X icon, closes #2386. I used [this image](http://iphonesoft.fr/images/_102013/boson_x_01.jpg) as reference.
=> Boson X icon (Steam)

Numix-Circle/48x48/apps/metronome.svg
A new metronome app
https://launchpad.net/metronome
=> Symlink for Metronome

Numix-Circle/48x48/apps/kleopatra.svg
"Certificate Manager and Unified Crypto GUI"
https://www.kde.org/applications/utilities/kleopatra/
Icon=kleopatra
=> Symlink for Kleopatra

Numix-Circle/48x48/apps/labyrinth.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2599.
=> Added labyrinth.svg

Numix-Circle-Light/16x16/panel, Numix-Circle-Light/22x22/panel, Numix-Circle-Light/24x24/panel, Numix-Circle/16x16/panel, Numix-Circle/22x22/panel, Numix-Circle/24x24/panel
When merging my PR in numix-base this one needs to be merged as well so that the symlinks work
=> Updates symlinks to new folder-structure

Numix-Circle/48x48/apps/mate-system-log.svg
=> Symlink for MATE Log Viewer

Numix-Circle/48x48/apps/foxit-reader.svg
Icon for foxit pdf reader. Fixes #2581
=> Adds foxit reader icon

Numix-Circle/48x48/apps/crawl-sdl_icon.svg, Numix-Circle/48x48/apps/vivaldi-beta.svg, Numix-Circle/48x48/apps/vso.svg
* Visual Studio Code (Another icon name) - Closes #2637
* Vivaldi Beta - Closes #2642
* Dungeon Crawl - Closes #2643
=> Several Symlinks

Numix-Circle/48x48/apps/blivet-gui.svg
GUI tool for storage configuration
https://github.com/rhinstaller/blivet-gui
=> Symlink for blivet-gui

Numix-Circle/48x48/apps/xt7-player-mpv.svg
A frontend for mpv
https://github.com/kokoko3k/xt7-player-mpv
=> Icon for Xt7-player-mpv

Numix-Circle/48x48/apps/din.svg
software musical instrument
http://dinisnoise.org/
**Alts:**
=> Icon for DIN Is Noise

Numix-Circle/48x48/apps/endless-sky.svg
A space exploration and combat game
http://endless-sky.github.io/
Icon=endless-sky
The AUR build however doesn't provide an icon currently.
=> Symlink for Endless Sky

Numix-Circle/48x48/apps/xcos.svg
Xcos icon from Scilab software. It was not included initially in
the pull request #1318 (issue #1012).
=> Xcos (Scilab) icon

Numix-Circle/48x48/apps/mmex.svg
Personal finance software
http://www.moneymanagerex.org/
mmex.desktop
Icon=/usr/share/icons/hicolor/scalable/apps/mmex.svg
=> Symlink for Money Manager Ex

Numix-Circle/48x48/apps/auale.svg
Oware board game
http://www.joansala.com/auale/en/
Icon=auale
=> Icon for Aualé

Numix-Circle/48x48/apps/steam_icon_221830.svg
Fixes numixproject/numix-icon-theme-circle#1308
Steam ID: 221830
=> Add icon for The Book of Unwritten Tales: Critter Chronicles

Numix-Circle/48x48/apps/steam_icon_215160.svg
Fixes numixproject/numix-icon-theme-circle#1308
Steam ID: 215160
=> Add icon for The Book of Unwritten Tales

Numix-Circle/48x48/apps/inkscape-logo.svg
Found this in the ``breeze`` theme. Maybe it's needed somewhere.
=> Inkscape symlink

Numix-Circle/48x48/apps/cudatext-256.svg, Numix-Circle/48x48/apps/cudatext.svg
text editor
https://github.com/Alexey-T/CudaText
=> Symlinks for CudaText

Numix-Circle/48x48/apps/anjuta6.svg
One from https://github.com/numixproject/numix-icon-theme/issues/827.
Whatever that is for.
=> anjuta6.svg

Numix-Circle/48x48/apps/kiwix.svg
Wikipedia offline reader
http://www.kiwix.org/wiki/Main_Page/en
=> Symlink for Kiwix

Numix-Circle/48x48/apps/steam_icon_219890.svg
**Antichamber Icon**
**SteamID:** *219890*
Original:
Pushed Icon:
*Note: It is hardcoded.*
=> Antichamber Icon

Numix-Circle/48x48/apps/steam_icon_241930.svg
**Middle Earth: Shadow of Mordor**
__SteamID:__ *241930*
=> Middle Earth: Shadow of Mordor icon

Numix-Circle/48x48/apps/cs-input-method.svg, Numix-Circle/48x48/apps/im-chooser.svg, Numix-Circle/48x48/apps/mintdrivers.svg, Numix-Circle/48x48/apps/mintinstall.svg, Numix-Circle/48x48/apps/mintnanny.svg, Numix-Circle/48x48/apps/mintsources.svg, Numix-Circle/48x48/apps/mintupdate.svg, Numix-Circle/48x48/apps/mintupload.svg
Well, not really 'add support', simply improve it a bit... I haven't tested this intensively.
=> This should add support for Linux Mint 17.3 with Cinnamon 2.8

Numix-Circle/48x48/apps/chrome-ajjmenfgmbpceneffopmikhahnkeebje-Default.svg
=> Inbox smylink

Numix-Circle/48x48/apps/midieditor.svg
http://midieditor.sourceforge.net/
=> Symlink for MidiEditor

Numix-Circle/48x48/apps/gddccontrol.svg
It's a monitor calibration tool
=> Add gddccontrol symlink

Numix-Circle/48x48/apps/playbox.svg
"A growing collection of board games"
http://sourceforge.net/projects/playbox/
=> Symlink for Playbox

Numix-Circle/48x48/apps/plotdigitizer.svg
http://plotdigitizer.sourceforge.net/
=> Symlink for Plot Digitizer

Numix-Circle/48x48/apps/fidocadj.svg
http://sourceforge.net/projects/fidocadj/
=> Symlink for FidoCADJ

Numix-Circle/48x48/apps/widemargin.svg
=> Fix for widemargin.svg

Numix-Circle/48x48/apps/KKEdit.svg, Numix-Circle/48x48/apps/KKEditRoot.svg
=> Icons for KKEdit

Numix-Circle/48x48/apps/firefox-esr.svg, Numix-Circle/48x48/apps/null_team.svg
=> Symlinks for Firefox ESR and YATE

Numix-Circle/48x48/apps/mahjong.svg
This one http://mahjong.julianbradfield.org/
=> Symlink for Mah-Jong

Numix-Circle/48x48/apps/org.gnome.Bijiben.svg, Numix-Circle/48x48/apps/org.gnome.Calendar.svg, Numix-Circle/48x48/apps/org.gnome.Cheese.svg, Numix-Circle/48x48/apps/org.gnome.Clocks.svg, Numix-Circle/48x48/apps/org.gnome.Documents.svg, Numix-Circle/48x48/apps/org.gnome.Hitori.svg, Numix-Circle/48x48/apps/org.gnome.Maps.svg, Numix-Circle/48x48/apps/org.gnome.Polari.svg, Numix-Circle/48x48/apps/org.gnome.Software.svg, Numix-Circle/48x48/apps/org.gnome.Todo.svg, Numix-Circle/48x48/apps/org.gnome.Weather.svg, Numix-Circle/48x48/apps/org.gnome.bijiben.svg, Numix-Circle/48x48/apps/org.gnome.clocks.svg
=> Symlinks for GNOME apps

Numix-Circle/48x48/apps/qTox.svg, Numix-Circle/48x48/apps/uTox.svg
As reported by @eduardomezencio.
=> Symlinks for qTox and uTox

Numix-Circle/48x48/apps/minuet.svg
A new music education app to be introduced with Applications 16.04
https://minuet.kde.org/
Original:
Pushed:
=> Icon for KDE Minuet

Numix-Circle/48x48/apps/steam_icon_222880.svg
**Game:** Insurgency
**SteamID:** 222880
=> Insurgency icon (Steam)

Numix-Circle/48x48/apps/com.gexperts.Terminix.svg, Numix-Circle/48x48/apps/terminix.svg
https://github.com/gnunn1/terminix
Original:
Pushed:
=> Icon for Terminix

Numix-Circle/48x48/apps/FoxitReader.svg
=> Fixes #2917

Numix-Circle/48x48/apps/gnuradio-grc.svg
http://gnuradio.org/redmine/projects/gnuradio/wiki/GNURadioCompanion
=> Symlink for GNU Radio Companion

Numix-Circle/48x48/apps/tageditor.svg
https://github.com/Martchus/tageditor
=> Symlink for tageditor

Numix-Circle/48x48/apps/fgo.svg
=> Symlink for FGo

Numix-Circle/48x48/apps/ddrescue-gui.svg
https://launchpad.net/ddrescue-gui
=> Symlink for ddrescue-gui

Numix-Circle/48x48/apps/accessories-screenshot.svg
Fixed lrsvg outlines and the bezel.
=> Outline fix for screenshot icon

Numix-Circle/48x48/apps/steam_icon_108200.svg, Numix-Circle/48x48/apps/steam_icon_11500.svg, Numix-Circle/48x48/apps/steam_icon_22010.svg, Numix-Circle/48x48/apps/steam_icon_22600.svg, Numix-Circle/48x48/apps/steam_icon_339280.svg, Numix-Circle/48x48/apps/steam_icon_40700.svg, Numix-Circle/48x48/apps/steam_icon_40710.svg, Numix-Circle/48x48/apps/steam_icon_409370.svg, Numix-Circle/48x48/apps/steam_icon_415890.svg, Numix-Circle/48x48/apps/steam_icon_427520.svg, Numix-Circle/48x48/apps/steam_icon_452280.svg, Numix-Circle/48x48/apps/steam_icon_57640.svg, Numix-Circle/48x48/apps/steam_icon_9420.svg
Note however that I've never used Steam, nor did I play those games.
I just looked up the icon names the way described in your tutorial video.
Hope it works this way.
=> Game symlinks

Numix-Circle/48x48/apps/rapidsvn.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2932
=> Icon for RapidSVN

Numix-Circle/48x48/apps/khangman.svg
=> Icon for KHangMan

Numix-Circle/48x48/apps/Caprine.svg
https://github.com/sindresorhus/caprine
=> Symlink for Caprine

Numix-Circle/48x48/apps/altyo.svg
https://github.com/linvinus/AltYo
=> Icon for AltYo

Numix-Circle/48x48/apps/xyscan.svg
http://rhig.physics.yale.edu/~ullrich/software/xyscan/
=> Symlink for xyscan

Numix-Circle/48x48/apps/vifm.svg
=> Symlink for viFM

Numix-Circle/48x48/apps/smb4k.svg
https://sourceforge.net/projects/smb4k/
=> Symlink for smb4k

Numix-Circle/48x48/apps/kcachegrind.svg
https://kcachegrind.github.io/html/Home.html
=> Icon for KCachegrind

Numix-Circle/48x48/apps/WorkerIcon48.svg, Numix-Circle/48x48/apps/maxima-icon.svg, Numix-Circle/48x48/apps/tkgate.svg
http://www.boomerangsworld.de/cms/worker/
https://sourceforge.net/projects/tkgate/
=> Symlinks for Maxima, Worker and tkgate

Numix-Circle/48x48/apps/AdvancedPhoto.svg, Numix-Circle/48x48/apps/colorgrab.svg, Numix-Circle/48x48/apps/gpxsee.svg, Numix-Circle/48x48/apps/kamule.svg
https://sourceforge.net/projects/advancedphoto/
http://opendesktop.org/content/show.php/KaMule?content=150270
https://github.com/tumic0/GPXSee
https://github.com/nielssp/colorgrab
=> Symlinks for AdvancedPhoto, Kamule, GPXsee, colorgrab

Numix-Circle/48x48/apps/opendict.svg
http://opendict.sourceforge.net/
=> Icon for OpenDict

Numix-Circle/48x48/apps/ffDiaporama.svg, Numix-Circle/48x48/apps/ffdiaporama.svg, Numix-Circle/48x48/apps/freeciv-modpack.svg
http://ffdiaporama.tuxfamily.org/
=> Symlinks for ffDiaporama and FreeCiv

Numix-Circle/48x48/apps/application-vidiot.svg, Numix-Circle/48x48/apps/vidiot.svg
https://sourceforge.net/projects/vidiot/
=> Symlink for Vidiot

Numix-Circle/48x48/apps/cuttlefish.svg
http://vizzzion.org/blog/2015/02/say-hi-to-cuttlefish/
=> Symlink for Cuttlefish

Numix-Circle/48x48/apps/gmplayer-dvb.svg
https://sourceforge.net/projects/gmplayer-dvb/
=> Symlink for GMPlayer-DVB

Numix-Circle/48x48/apps/robocode.svg
=> Icon for Robocode

Numix-Circle/48x48/apps/netgen.svg, Numix-Circle/48x48/apps/netgen16x16.svg
https://sourceforge.net/projects/netgen-mesher/
=> Icon for Netgen

Numix-Circle/48x48/apps/jftp.svg, Numix-Circle/48x48/apps/wpa_gui.svg
http://w1.fi/wpa_supplicant/
http://j-ftp.sourceforge.net/
=> Symlinks for wpa_gui and JFtp

Numix-Circle/48x48/apps/regina.svg
http://regina.sourceforge.net/
``netgen.svg`` had the symbol duplicated.
=> Icon for Regina, fix for Netgen

Numix-Circle/48x48/apps/fcitx.svg
=> Better link for fcitx

Numix-Circle/48x48/apps/reddit-is-a-dead-bird.svg
https://github.com/samdroid-apps/something-for-reddit
=> Symlink for Something For Reddit

Numix-Circle/48x48/apps/wpcom.svg
https://apps.wordpress.com/desktop/
=> link for wordpress.com desktop app

Numix-Circle/48x48/apps/min.svg
https://github.com/minbrowser/min
=> Icon for Min

Numix-Circle/48x48/apps/remotebox.svg
http://remotebox.knobgoblin.org.uk/
=> Icon for RemoteBox

Numix-Circle/48x48/apps/yapysudoku.svg
https://sourceforge.net/projects/yapysudoku/files/yapysudoku/
=> Symlink for yapysudoku

Numix-Circle/48x48/apps/LogAnalyzer.svg, Numix-Circle/48x48/apps/gimagereader.svg, Numix-Circle/48x48/apps/ocrfeeder.svg, Numix-Circle/48x48/apps/yagf.svg
https://github.com/pbek/loganalyzer
Additional cleanups for gimagereader, ocrfeeder and yagf.
=> Icon for LogAnalyzer

Numix-Circle/48x48/apps/ubuntusoftware.svg
=> Symlink for Ubuntu Software

Numix-Circle/48x48/apps/voxelands.svg
http://www.voxelands.com/
gradient bug fix for ``freeminer.svg``
=> Icon for Voxelands

Numix-Circle/48x48/apps/huayra-motion.svg
https://github.com/HuayraLinux/huayra-stopmotion
=> Icon for huayra-stopmotion

Numix-Circle/48x48/apps/angrysearch.svg
https://github.com/DoTheEvo/ANGRYsearch
*+* Bigger symbol for ``gpk-log.svg``.
=> Icon for angrysearch

Numix-Circle/48x48/apps/gromit-mpx.svg
https://github.com/bk138/gromit-mpx
=> Symlink for gromit-mpx

Numix-Circle/48x48/apps/veracrypt.svg
I used contours to avoid the tiny gaps between triangles.
=> Icon for veracrypt. Fixes #2803

Numix-Circle/48x48/apps/xware-desktop.svg
https://github.com/Xinkai/XwareDesktop
=> Icon for Xware Desktop

Numix-Circle/48x48/apps/fs-uae.svg
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2913
=> Icon for fs-uae

Numix-Circle/48x48/apps/terminatorX.svg
=> Icon for terminatorX

Numix-Circle/48x48/apps/QMPlay2.svg
https://github.com/zaps166/QMPlay2
=> Icon for QMPlay2

Numix-Circle/48x48/apps/deepin-appstore.svg
=> Symlink for Deepin appstore

Numix-Circle/48x48/apps/plex-icon-256.svg
https://github.com/RasPlex/OpenPHT
=> Symlink for OpenPHT

Numix-Circle/48x48/apps/WMail.svg
https://github.com/Thomas101/Wmail
=> Symlink for WMail

Numix-Circle/48x48/apps/yt-dl-gtk.svg
https://sourceforge.net/projects/youtube-dl-gtk/
=> Symlink for yt-dl-gtk

Numix-Circle/48x48/apps/filerunner.svg
https://sourceforge.net/projects/filerunner/
=> Symlink for filerunner

Numix-Circle/48x48/apps/n-puzzle.svg
=> Symlink for n-puzzle

Numix-Circle/48x48/apps/indicator-stickynotes.svg
=> Icon for indicator-stickynotes

icons/48/chrome-efjnaogkjbogokcnohkmnjdojkikgobo-Default.svg
=> Bigger symbol for Google Photos

icons/48/plexmediamanager.svg
Removed duplicate baseplate. Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/4.
=> Fix for Plex

icons/48/discord-canary.svg
Fixes #3121 
Plus slight fix for the existing icon.
=> Fixes #3121

icons/48/webtorrent-desktop.svg
https://github.com/feross/webtorrent-desktop
=> Icon for webtorrent-desktop

Numix-Circle/48x48/apps/rationalplan-multi.svg, Numix-Circle/48x48/apps/rationalplan-project.svg, Numix-Circle/48x48/apps/rationalplan-single.svg
Hi everybody!
I made icons for RationalPlan as requested in #3270 
I hope everything is ok :)
=> Icons for RationalPlan

icons/48/cdemu-client.svg
https://sourceforge.net/projects/cdemu/
Needs a symlink ``gcdemu``.
=> Icon for cdemu

icons/48/soundnode.svg
https://github.com/Soundnode/soundnode-app
Alts:
=> Icon for soundnode

icons/48/harmony.svg
https://github.com/vincelwt/harmony
Alt:
=> Icon for harmony
